[functions.melhor-envios-quote]
enabled = true
verify_jwt = true
import_map = "./functions/melhor-envios-quote/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/melhor-envios-quote/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/melhor-envios-quote/*.html" ]

[functions.rag-indexer]
enabled = true
verify_jwt = true
import_map = "./functions/rag-indexer/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/rag-indexer/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/rag-indexer/*.html" ]

[functions.ai-chat]
enabled = true
verify_jwt = true
import_map = "./functions/ai-chat/deno.json"
entrypoint = "./functions/ai-chat/index.ts"

[functions.process-knowledge-base]
enabled = true
verify_jwt = true
import_map = "./functions/process-knowledge-base/deno.json"
entrypoint = "./functions/process-knowledge-base/index.ts"
