[functions.melhor-envios-quote]
enabled = true
verify_jwt = true
import_map = "./functions/melhor-envios-quote/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/melhor-envios-quote/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/melhor-envios-quote/*.html" ]

[functions.checkout]
enabled = true
verify_jwt = true

[functions.mercado-pago-webhook]
enabled = true
verify_jwt = false
